- name: Initialize ckan db
  action: command ckan db init

- name: Initialize ckan report db
  action: command ckan --plugin=ckanext-report report initdb

- name: Initialize ckan archiver db
  command: ckan --plugin=ckanext-archiver archiver init
  tags: skip_ansible_lint

- name: Initialize ckan qa db
  command: ckan --plugin=ckanext-qa qa init
  tags: skip_ansible_lint

- name: Initialize ckan ga-report db
  command: ckan --plugin=ckanext-ga-report initdb
  tags: skip_ansible_lint
